class_name AnsiParser
extends TextConsole

const ESC := 27
const CSI := "%c[" % ESC
# CURSOR
const CRSR_HOME      := "H"
const CRSR_MOVE1     := "H"
const CRSR_MOVE2     := "f"
const CRSR_UP        := "A"
const CRSR_DOWN      := "B"
const CRSR_RIGHT     := "C"
const CRSR_LEFT      := "D"
const CRSR_COL0_DOWN := "E"
const CRSR_COL0_UP   := "F"
const CRSR_MOVE_COL  := "G"
const CRSR_SCROLL_UP := "M"
const CRSR_SAVE_POS  := "s"
const CRSR_REST_POS  := "u"
# ERASE
const ERAS_CRSR_EOS  := "0J"
const ERAS_CRSR_BOS  := "1J"
const ERAS_SCREEN    := "2J"
const ERAS_CRSR_EOL  := "0K"
const ERAS_CRSR_BOL  := "1K"
const ERAS_LINE      := "2K"
# GRAPHICS MODES
const GRFX_RESET     := "0m"
const GRFX_BOLD      := "1m"
const GRFX_DIMMED    := "2m"
const GRFX_ITALIC    := "3m"
const GRFX_UNDERLINE := "4m"
const GRFX_BLINKING  := "5m"
const GRFX_INVERSE   := "7m"
const GRFX_HIDDEN    := "8m"
const GRFX_STRIKEOUT := "9m"
# FOREGROUND COLORS
const COLOR_RESET        := "0m"
const COLR_FG_DEFAULT    := "39m"
const COLR_FG_BLACK      := "0;30"
const COLR_FG_BLUE       := "0;34"
const COLR_FG_GREEN      := "0;32"
const COLR_FG_CYAN       := "0;36"
const COLR_FG_RED        := "0;31"
const COLR_FG_MAGENTA    := "0;35"
const COLR_FG_BROWN      := "0;33"
const COLR_FG_WHITE      := "0;37"
const COLR_FG_GRAY       := "1;30"
const COLR_FG_BR_BLUE    := "1;34"
const COLR_FG_BR_GREEN   := "1;32"
const COLR_FG_BR_CYAN    := "1;36"
const COLR_FG_BR_RED     := "1;31"
const COLR_FG_BR_MAGENTA := "1;35"
const COLR_FG_BR_BROWN   := "1;33"
const COLR_FG_BR_WHITE   := "1;37"
# BACKGROUND COLORS
const COLR_BG_BLACK      := "40"
const COLR_BG_BLUE       := "44"
const COLR_BG_GREEN      := "42"
const COLR_BG_CYAN       := "46"
const COLR_BG_RED        := "41"
const COLR_BG_MAGENTA    := "45"
const COLR_BG_BROWN      := "43"
const COLR_BG_WHITE      := "47"
const COLR_BG_GRAY       := "5;40"
const COLR_BG_BR_BLUE    := "5;44"
const COLR_BG_BR_GREEN   := "5;42"
const COLR_BG_BR_CYAN    := "5;46"
const COLR_BG_BR_RED     := "5;41"
const COLR_BG_BR_MAGENTA := "5;45"
const COLR_BG_BR_BROWN   := "5;43"
const COLR_BG_BR_WHITE   := "5;47"

func _ready():
	pass # Replace with function body.
